### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by HeljaeRaeisaenen** [astranero/music-generator#1]
Repository cloned 15. Feb at 11.18

- Very good UI, cool graphics.
- Error in tasks.py, the `poetry run invoke start` results in error
- In class UI, both ` _initiate_markov` and `_generate_music` have code that asks the user for a value for ‘depth’ and deals with incorrect depth value. This seems like copypaste that could be extracted into its own method.
- in class Markov, in method `generate_melody`, there’s code that resembles the classic search method for Trie. It could be made into its own method of the Trie or of the Markov class. This would make the `generate_melody` simpler and reduce copypaste. I mean this:

```
for note in prefix_notes:
    if not node.terminal and note in node.children:
        node = node.children[note]
...
for note in current:
    if note in current_node.children and not current_node.terminal:
          current_node = current_node.children[note]
```
- In class Markov, in `generate_melody`, there’s this try-catch block:

```
try:
	node = current_node.children[new_note]
except KeyError:
         node = self._trie.get_root()
```
I personally think it would make sense for  `get_random_note` to return None if the node doesn’t have any children. Then, if None is returned, the code could run `get_random_note` again with the trie root as its arg.  This would eliminate the try-except. 
	I think having a try-except block in a place where a KeyError is easily avoidable is kind of ugly, but this is just my opinion and I don't kow what's best practice.
- Good modularisation and OOP practice, the project seems to be going well

**Comment by astranero** [comment]
Thank you for your valuable insights, I applied everything to my code, and it looks so much better now. Great review! :)
